"$var";
" x $var";
" x {$var}";
"#x$var";
" # x $var#x";
" #{$var->func("arg")} #";
" x {$var->prop} #x";
" # x {$var->prop["key"]}# x";
" # x {$var->prop["key:"."key: {$var->func("arg")}"]}# x";
" # x \{$var->prop}# x";
