(script
  (using_statement
    (binary_expression
      left: (variable)
      right: (new_expression
        (qualified_identifier
          (identifier))
        (arguments)))
    (binary_expression
      left: (variable)
      right: (new_expression
        (qualified_identifier
          (identifier))
        (arguments
          (argument
            (string
              (string_body)))
          (argument
            (string
              (string_body))))))
    (compound_statement)))
