(script
  (expression_statement
    (binary_expression
      left: (string
        (string_body))
      right: (binary_expression
        left: (binary_expression
          left: (string
            (string_body))
          right: (binary_expression
            left: (string
              (string_body))
            right: (string
              (string_body))))
        right: (binary_expression
          left: (binary_expression
            left: (string
              (string_body))
            right: (string
              (string_body)))
          right: (binary_expression
            left: (binary_expression
              left: (binary_expression
                left: (binary_expression
                  left: (string
                    (string_body))
                  right: (string
                    (string_body)))
                right: (string
                  (string_body)))
              right: (string
                (string_body)))
            right: (binary_expression
              left: (binary_expression
                left: (binary_expression
                  left: (binary_expression
                    left: (binary_expression
                      left: (string
                        (string_body))
                      right: (string
                        (string_body)))
                    right: (string
                      (string_body)))
                  right: (string
                    (string_body)))
                right: (string
                  (string_body)))
              right: (binary_expression
                left: (binary_expression
                  left: (string
                    (string_body))
                  right: (string
                    (string_body)))
                right: (binary_expression
                  left: (binary_expression
                    left: (binary_expression
                      left: (string
                        (string_body))
                      right: (string
                        (string_body)))
                    right: (string
                      (string_body)))
                  right: (binary_expression
                    left: (binary_expression
                      left: (binary_expression
                        left: (string
                          (string_body))
                        right: (string
                          (string_body)))
                      right: (string
                        (string_body)))
                    right: (binary_expression
                      left: (string
                        (string_body))
                      right: (string
                        (string_body)))))))))))))
