(script
  (expression_statement
    (binary_expression
      left: (subscript_expression
        (variable)
        (string
          (string_body)))
      right: (as_expression
        left: (integer)
        right: (type_specifier))))
  (expression_statement
    (binary_expression
      left: (subscript_expression
        (variable)
        (string
          (string_body)))
      right: (as_expression
        left: (null)
        right: (type_specifier)))))
