(script
  (expression_statement
    (require_expression
      (parenthesized_expression
        (binary_expression
          left: (qualified_identifier
            (identifier))
          right: (string
            (string_body))))))
  (expression_statement
    (require_expression
      (parenthesized_expression
        (binary_expression
          left: (qualified_identifier
            (identifier))
          right: (string
            (string_body)))))))
