(script
  (function_declaration
    name: (identifier)
    (parameters)
    return_type: (type_specifier)
    body: (compound_statement
      (expression_statement
        (yield_expression
          (string
            (string_body))))
      (expression_statement
        (yield_expression
          (yield_expression
            (element_initializer
              (string
                (string_body))
              (integer)))))
      (expression_statement
        (yield_expression
          (element_initializer
            (integer)
            (string
              (string_body))))))))
